### ISSUE TITLE
Does this support generating binary plists?

### ISSUE THREAD

**Issue by futuretap** [MSchmidt/CFPropertyList-rails#4]
If yes it would be great to document it in the Readme.

**Comment by MSchmidt** [comment]
Yes this actually supports binary plists exclusively. The introduction in the README says:

```
Render CFPropertyLists in Rails3 apps. Plists are generated in binary format.

Binary Plists are small in size and therefore ideal for usage with mobile iOS clients, such as iPhone and iPad.
```

But this gem hasn't been updated in quite some time and I'm not using this in any production software myself at the time.

**Comment by futuretap** [comment]
I'm sorry, I didn't notice because QuickLook just works and BBEdit converts binary plists on-the-fly.
Works great, thanks.
